LiteraFlow/Controllers/MyBooksController.cs
using LiteraFlow.Web.BL.Books;
using LiteraFlow.Web.Middleware;
using LiteraFlow.Web.Services;

namespace LiteraFlow.Web.Controllers;

//TODO Delete opened book on Button

[UserAuthorized]
[ResponseCache(Duration = 3600, Location = ResponseCacheLocation.None, NoStore = true)]
public class MyBooksController : Controller
{
    private readonly IBooks booksBL;
    private readonly ICurrentUser currentUser;

    public MyBooksController(IBooks books, ICurrentUser currentUser)
    {
        this.booksBL = books;
        this.currentUser = currentUser;
    }


    [HttpGet]
    [Route("/mybooks")]
    public async Task<IActionResult> Index()
    {
        var books = await GetBooks();

        if (books == null)
            return Redirect("/profile");

        return View(BookMapper.ModelToViewModel(books).ToList());
    }


    public async Task<IActionResult> Details(int id, [FromServices] ICacheService cache)
    {
        if (!await ValidateBook(id))
            return BadRequest("Ошибка загрузки");
        
        var book = await booksBL.Get(id);

        // Load chapters
        var chapters = await booksBL.GetChaptersAsync(id);

        // Add template chapter
        if (chapters.Count == 0) chapters.Add(new()
        {
            Title = "Глава 1",
            SerialNumber = 1,
            BookId = id,
        });

        cache.Set(CacheConstants.BOOK_CHAPTERS, chapters, 3600);

        
        var viewModel = new BookAndChaptersViewModel 
        { 
            Book = BookMapper.ModelToViewModel(book), 
            Chapters = ChapterMapper.ModelToViewModel(chapters)
        };


        return View(viewModel);
    }


    [HttpPost]
    public async Task<IActionResult> GetChapterText(int? chapterId, int bookId, [FromServices] ICacheService cache)
    {
        if (!await ValidateBook(bookId))
            return BadRequest("Ошибка загрузки");

        // null в случае только что созданной главы книги
        if (chapterId == null)
            return Json(String.Empty);


        List<ChapterModel>? chapters = cache.GetOrNull<List<ChapterModel>?>(CacheConstants.BOOK_CHAPTERS);
        if(chapters == null)
        {
            var chaptersFromDb = await booksBL.GetChaptersAsync(bookId);
            cache.Remove(CacheConstants.BOOK_CHAPTERS);
            cache.Set(CacheConstants.BOOK_CHAPTERS, chaptersFromDb, 3600);
        }

        // Если глава из запроса пользователя не имеется в книге 
        if (!Enumerable.Any(chapters, c => c.ChapterId == chapterId))
            return BadRequest("Ошибка загрузки");

        string txt = await booksBL.GetChapterText((int)chapterId);
        return Json(txt);

    }


    [HttpPost]
    [Route("/mybooks/book/savesettings")]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> SaveSettings(BookViewModel book)
    {
        if (!ModelState.IsValid) 
            return View(book);

        await booksBL.UpdateAsync(BookMapper.ViewModelToModel(book));

        return Ok();
    }


    [HttpPost]
    [Route("/mybooks/book/saveimg")]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> SaveBookImage(int bookId)
    {
        bool isExistsFile = Request.Form?.Files.Any() ?? false;

        if (isExistsFile) 
            return BadRequest();

        if(!await ValidateBook(bookId))
            return BadRequest();

        // Save the Image
        string? imgPath = await WebFile.SaveAsync(Request.Form.Files[0], WebFile.BOOK_PATH);
        if(imgPath == null)
        {
            return BadRequest();
        }

        await booksBL.UpdateImageAsync(imgPath, bookId);


        return Redirect($"/mybooks/details/{bookId}");
    }


    [HttpPost]
    public async Task<IActionResult> SaveChapter([FromBody] ChapterViewModel vm)
    {
        //TODO Check that user have this book and chapterid
        if(!ModelState.IsValid) 
            return View();


        ChapterModel model = new()
        {
            BookId = (int)vm.BookId,
            Title = vm.Title,
            Text = vm.Text,
            ChapterId = vm.ChapterId,
            AmountLetters = vm.Text.Length,
            SerialNumber = 1,
            UpdatedOn = DateTime.Now
        };

        int? id = await booksBL.UpdateOrCreateChapterAsync(model);

        if(id is null)
            return Problem();

        //TODO Update book's amount letter

        return Ok();
    }


    private async Task<List<BookModel>?> GetBooks()
    {
        var profile = await currentUser.GetProfile();

        if (profile.ProfileId == null)
            return null;

        var books = await booksBL.GetUserBooks((int)profile.ProfileId);
        return books;
    }


    /// <summary>
    /// Сверяет id книги и соответствия профилю пользователя
    /// </summary>
    /// <returns>Redirects</returns>
    private async Task<bool> ValidateBook(int bookId)
    {
        var books = await GetBooks();

        if (books == null)
            return false;

        var book = await booksBL.Get(bookId);

        if (book?.BookId == null)
            return false;


        //если пытается зайти на чужую книгу по id
        if (!Enumerable.Any(books, book => book.BookId == bookId))
            return false;

        return true;
    }



}

LiteraFlow/Views/Mybooks/Details.cshtml
@model BookAndChaptersViewModel


  <div class="row">
    <div id="leftCol" class="col-12 col-lg-8 pe-4">

        <div class="row mb-3">
            <div class=" d-flex flex-wrap justify-content-start">
                <select class="selector" id="chapterSelector">
                    @for (int i = 0; i < @Model.Chapters.Count; i++)
                    {
                        <option value="@Model.Chapters[i].ChapterId">@Model.Chapters[i].Title</option>
                    }
                    
                </select>
                <span class="col-auto">
                    <i class="fa fa-plus text-black h-auto" style="cursor:pointer;" id="createChapterBtn" aria-hidden="true"></i>

                </span>
                
            </div>

        </div>

        <form id="ChapterForm">
            @Html.AntiForgeryToken()
            
            <label class="mb-3">
                <div>Заголовок</div>
                <input id="chapterTitle" value="@Model.Chapters[^1].Title" />

            </label>

            <div class="mb-3">
                <label>Текст</label>
                <p class="chapter_redactor" contenteditable="true" id="chapterText"></p>
            </div>


            <input type="hidden" id="chapterIdStore" readonly />
            <input type="hidden" id="bookIdStore" name="Book.BookId" value="@Model.Book.BookId" readonly />

            <button type="button" id="saveChapterBtn">Сохранить</button>
        </form>

    </div>

    <div id="rightCol" class="ps-4 col-0 col-lg-4 d-flex flex-wrap justify-content-center">
        <div class="w-100">
            <form method="post" action="savesettings">
                @Html.AntiForgeryToken()
                <div class="mb-3">
                    <label class="form__label">Название</label>
                    <input class="form__input" name="Title" value="@Model.Book.Title" type="text" />
                </div>
                <div class="mb-3">
                    <label class="form__label">Описание</label>
                    <p class="form__p" name="Description" value="@Model.Book.Description" type="text" contenteditable="true">@Model.Book.Description</p>
                </div>
                <div class="mb-3">
                    <label class="form__label">Заметка</label>
                    <input class="form__input" name="AuthorNote" value="@Model.Book.AuthorNote" type="text" />
                </div>
                <div class="mb-3">
                    <label class="form__label">Цена</label>
                    <input class="form__input" name="Price" value="@Model.Book.Price" type="text" />
                </div>
                <input type="hidden" name="BookId" id="bookId" value="@Model.Book.BookId" />
                <button type="submit">Сохранить</button>
            </form>
        </div>
        


    </div>

    @* TODO Amount of letters *@

    <div id="success-noti" class="alert alert-success d-none align-items-center w-
position-absolute align-self-start" role="alert">
        <i class="fa fa-check-circle text-black me-3" aria-hidden="true"></i>
        <label>
            Пример уведомления об успехе с иконкой
        </label>
    </div>

    <div class="toggle-button" id="toggleButton">
        <i style="cursor:pointer;" id="iconToggler" class="fa fa-angle-double-right text-black" aria-hidden="true"></i>
    </div>

    <button id="showNotification">Показать уведомление</button>

    
    

</div>  

@section Scripts{
    <script defer>     
        $(document).ready(function () {

            const chapterSelector = document.getElementById("chapterSelector");
            const chapterText = document.getElementById("chapterText");
            const chapterTitle = document.getElementById("chapterTitle");
            const chapterId = document.getElementById("chapterIdStore");
            

            function LoadChapterText() {
                let SelectedChapterId = chapterSelector.options[chapterSelector.selectedIndex].value;
                let ThisBookId = $("#bookIdStore").val();

                console.log(ThisBookId);
                console.log(SelectedChapterId);

                chapterId.value = SelectedChapterId;
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("GetChapterText")",
                    dataType: "json",
                    data: { chapterId: SelectedChapterId, bookId: ThisBookId },
                    success: function (result) {
                        chapterText.textContent = result;
                    },
                    error: function (req, status, error) {
                        //TODO refactor this
                        chapterText.textContent = status;
                    }
                });
            };

            function ChapterSelected(){

                LoadChapterText();
                chapterTitle.value = chapterSelector.options[chapterSelector.selectedIndex].textContent;
            };

            $("#saveChapterBtn").click(function (){
                let chapter = {
                    BookId: $("#bookId").val(),
                    Title: $("#chapterTitle").val(),
                    Text: $("#chapterText").text(),
                    ChapterId: $("#chapterIdStore").val() || null,                    
                };

                $.ajax({
                    url: '@Url.Action("SaveChapter", "MyBooks")',
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(chapter),
                    success: showSuccessNotification,
                    error: function (req, status, error) {
                        //TODO popup
                        chapterText.textContent = status;
                    }
                }); 
            });


            chapterSelector.addEventListener("change", ChapterSelected);

            chapterSelector.options[chapterSelector.options.length - 1].selected = true;
            ChapterSelected();

            // Logic of creating new chapter button
            const createChapterBtn = document.getElementById("createChapterBtn");

            createChapterBtn.addEventListener('click', function () {
                let newOption = document.createElement("option");
                newOption.textContent = "Новая глава";
                newOption.value = "Новая глава";
                newOption.selected = true;
                chapterSelector.appendChild(newOption);

                chapterText.textContent = "Текст";
                chapterTitle.value = "Новая глава";
                chapterId.value = null;
            });

            $("#toggleButton").click(function () {
                $("#leftCol").toggleClass("col-12 col-lg-12");
                $("#rightCol").toggleClass("col-0 col-lg-0 d-none");
                
                
                
                // Измените текст кнопки на основе состояния
                if ($("#leftCol").hasClass("col-12")) {
                    $("#iconToggler").removeClass("fa-angle-double-left");
                } else {
                    $("#iconToggler").addClass("fa-angle-double-left");
                }
            });

            function showSuccessNotification() {
                $("#success-noti").fadeIn(400); // Плавное появление блока
                setTimeout(function () {
                    $("#success-noti").fadeOut(400); // Плавное исчезновение блока через некоторое время (например, 3 секунды)
                }, 3000);
            }

            $("#showNotification").click(function () {
                showSuccessNotification();
            });


        });
    </script>
}

LiteraFlow/Views/Mybooks/Index.cshtml
@model List<BookViewModel>


<div class="container">
    
    


    <div class="books_block d-flex flex-wrap justify-content-center">
         @foreach (var book in Model)
        {
            <a class="p-0 m-0 w-100" asp-action="Details" asp-route-id="@book.BookId">
                <div class="book__card w-100  bg-secondary row p-0 m-0 mb-2 d-flex">
                
                    <div class="p-0 m-0 w-auto">
                        <img class="book__card_image" src="/images/mock/default_book_pic.jpg" alt="">
                    </div>

                    <div class="col p-0 m-0">
                        <label class="book__card_title w-100">@book.Title</label>
                        <label>@book.Description</label>
                    </div>

                </div>
            </a>
                  
        } 
        

    </div>

    <div>
        <a href="/newbook/basic">
            <button class="btn_dark">+</button>
        </a>

    </div>

    
</div>